############# chinese navigation ##############

# main menu
[[main]]
name = "主页"
url = "/"
weight = 1

[[main]]
name = "关于我"
url = "/about"
weight = 2


[[main]]
name = "个人项目"
url = "/project"
weight = 3


[[main]]
name = "文章记录"
url = "/blog"
weight = 4

[[main]]
name = "生活记录"
url = "/life"
weight = 5



[[main]]
parent = "其他"
name = "Md编写说明"
url = "/elements"


[[main]]
parent = "其他"
name = "文字分类汇总"
url = "/categories"



# footer menu
# [[footer]]
# name = "About"
# url = "/about"
# weight = 1

[[footer]]
# name = "Elements"
# url = "/elements"
# weight = 2

[[footer]]
# name = "Privacy Policy"
# url = "/privacy-policy"
# weight = 3
