############# English navigation ##############

# main menu
# [[main]]
# name = "Main Page"
# url = "/"
# weight = 1



[[main]]
name = "Project"
url = "/projects"
weight = 1


[[main]]
name = "About Web"
url = "/about"
weight = 2

# [[main]]
# parent = "Other"
# name = "MD"
# url = "/elements"


# [[main]]
# parent = "Other"
# name = "Categories"
# url = "/categories"



# footer menu
# [[footer]]
# name = "About"
# url = "/about"
# weight = 1

[[footer]]
# name = "Elements"
# url = "/elements"
# weight = 2

[[footer]]
# name = "Privacy Policy"
# url = "/privacy-policy"
# weight = 3
