############# English navigation ##############

# main menu
[[main]]
name = "主页"
url = "/"
weight = 1

[[main]]
name = "关于我"
url = "/about"
weight = 2


[[main]]
weight = 3
name = "学习记录"
url = "/blog"

[[main]]
weight = 3
name = "生活记录"
url = "/life"


[[main]]
name = "Md编写说明"
url = "/elements"
weight = 4


[[main]]
parent = "其他"
name = ""
url = ""


[[main]]
parent = "其他"
name = "Authors"
url = "/authors"

[[main]]
parent = "其他"
name = "Categories"
url = "/categories"

[[main]]
parent = "其他"
name = "404 Page"
url = "/404"


# footer menu
# [[footer]]
# name = "About"
# url = "/about"
# weight = 1

[[footer]]
# name = "Elements"
# url = "/elements"
# weight = 2

[[footer]]
# name = "Privacy Policy"
# url = "/privacy-policy"
# weight = 3
