#################### default parameters ############################

# favicon 图标路径设置
favicon = "images/favicon.png"

# logo 图标路径设置（默认和深色模式）
logo = "images/logo.png"
logo_darkmode = "images/logo-darkmode.png"

# logo 尺寸设置。可以用 `px` 或 `x` 表示尺寸，例如 "100px"。注意：对于 .svg 文件，logo_width 不生效
logo_width = "160px"
logo_height = "32px"

# 如果 logo_webp 设置为 false，则不会生成 logo 的 WEBP 版本。默认值为 true
logo_webp = true

# logo_text 当 logo 图片丢失时显示的文本
logo_text = "LeeZChuan"

# 导航栏是否固定在页面顶部
navbar_fixed = true

# 主题模式切换开关
theme_switcher = true
theme_default = "system" # 可选 [light/dark/system]

# 主内容部分的栏目（例如博客）
mainSections = ["blog","life"]

# 联系表单的提交操作
# contact_form_action = "#" # 联系表单可以集成 [https://airform.io/] 或 [https://formspree.io]

# Google 标签管理器
google_tag_manager = "" # 示例: G-XXXXXXXXXX

# Google 广告代码
google_adsense = ""     # 示例: ca-pub-xxxxxxxxxxxxxxxx

# 自定义脚本代码，可嵌入HTML代码，示例: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""

# 版权声明
# copyright = "由[Zeon Studio](https://zeon.studio)设计，[LeeZChuan](https://github.com/LeeZChuan)改造"

# 预加载器模块配置
[preloader]
enable = false
preloader = "" # 可使用 jpg, png, svg 或 gif 格式的文件

# 导航按钮配置
[navigation_button]
enable = false
label = ""
link = ""

# 搜索模块配置
[search]
enable = true
primary_color = "#121212"
include_sections = ["blog","life"]
show_image = true
show_description = true
show_tags = true
show_categories = true

# 公告模块配置
[announcement]
enable = false
expire_days = 7
content = "您在部署时必须替换 **hugo.toml** 文件中的 **baseURL**，您可以从 **params.toml** 文件管理此公告。"

# SEO meta 数据，用于 OpenGraph / Twitter Card
[metadata]
keywords = ["Boilerplate", "Hugo"]
description = "Hugo & Tailwindcss 启动模板"
author = "zeon.studio"
twitter = "zeon_studio"
image = "images/og-image.png"

# 网站验证设置
[site_verification]
google = ""   # Google 验证码
bing = ""     # Bing 验证码
baidu = ""    # 百度验证
facebook = "" # Facebook 验证
mastodon = "" # Mastodon 验证

# Cookie 同意模块配置
[cookies]
enable = false
expire_days = 60
content = "本网站使用 cookies，继续使用即表示同意。"
button = "我接受"

# Mermaid 图表设置
[mermaid]
js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'

######################## 侧边栏展示内容 #########################
[widgets]
sidebar = ["categories", "tags"]

# Google 地图设置
[google_map]
enable = false
map_api_key = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# 订阅模块设置
[subscription]
enable = false
# Mailchimp 订阅表单设置
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # 替换为自己的URL
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"