name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # 监控 main 分支的提交

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 安装 Node.js 和 PostCSS
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 安装最新版本的 Node.js

      - name: Install PostCSS and other dependencies
        run: |
          npm install postcss postcss-cli autoprefixer

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build website
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # 这是 Hugo 生成的静态文件的目录